### ISSUE TITLE
Hiding a page from navigation makes the nav-prev & nav-next arrows disappear

### ISSUE THREAD

**Issue by adioni** [typemill-resources/learn#3]
If I chose "Hide page from navigation" from the meta tab and clear the site cache, the navigation arrows disappear for some reason. 

Checking the html code with Ctrl+U, the

```
<a class="nav nav-prev" href="/section1" title="Section1"> <i class="fa fa-chevron-left"></i></a>
<a class="nav nav-next" href="/section3" title="Section3" style="margin-right: 0px;"><i class="fa fa-chevron-right"></i></a>
```

part is somehow completely removed and the `<div id="navigation"></div>` section just becomes empty.

I can "fix" it by having zero hidden pages and clearing the cache again, but having the option to hide certain pages from navigation and have the theme functionality working as intended would definitely be preferable.

**Comment by trendschau** [comment]
Yes, there are some problems with this feature, it is a bit tricky so I have to find some time for a solution. But I am not sure If I understand your problem description. If I hide a page, then: 

* It is hidden from frontend main navigation (correct)
* It should be hidden from paging of the previous and next pages (there is a bug I think, see screenshot)
* On the hidden page itself, there is a main navigation, but there is are no pagings at all, which is ok for a hidden page, I think. 

Is it the second problem that you are adressing?

![page-missing](https://user-images.githubusercontent.com/2714547/122173247-e00d4080-ce81-11eb-9f4c-bd2cd16f4ae6.png)

**Comment by adioni** [comment]
Hello thanks for quick response looking into this. 

What I'm seeing is not really affecting the hidden page itself but rather somehow is affecting the layout that is applied for all the other pages. I spun up a fresh typemill install with the learn theme and recorded the steps I took and issue I'm seeing. Hopefully this helps clarify things:

['Hide Page from Navigation' steps and resultant issue](https://postimg.cc/mc0vHb3Y)

**Comment by trendschau** [comment]
ahhh, thank you, that is clarifying! I will have a look into it. Does the paging appear again if you reload the page in the browser several times? And does this behavior only appear if you delete the cache with the button in the admin area? The cache button deletes all cache files of the system and sometimes it takes some page refreshs to recreate the cache files completely. Instead of using the cache button in the admin area, you can also hard refresh the page in the frontend. That triggers the system to recreate the navigation cache, but it keeps a lot of other cache files, so in most cases this is more useful.

Anyway, I will try to reproduce the behavior and look if I can find a bug there. Thank you for the detailed reporting!

**Comment by adioni** [comment]
Reloading the page several time--regularly or via a hard refresh ( Shift|Ctrl F5 )--has no effect.

Oh forget  mention before: The reason I've been using the 'delete the cache' button in the admin area is because that is the only way I've been seemingly able to get the hidden page to actually become hidden on the frontend. Otherwise checking and saving "Hide page from navigation" doesn't seem to work (even after refreshing the site multiple times in the browser [regularly or via a hard refresh]).

**Comment by trendschau** [comment]
ok, thank you, the navigation is cached for 10 minutes, so if you change something like hiding/adding/deleting the page, then it will be shown in the frontend after 10 minutes latest, or if you refresh the page/cache in the browser. I use the reload current page button of firefox for it. 

I think I found the bug, it is related to folders, unfortunately the logic for hiding pages out of the navigation structure is pretty complicated in the backend (to be honest I would not create that feature again if I had the choice today). Anyway, I will try to fix it (and the missing links paging on the previous and the next page after a hidden element) for the next release.

**Comment by trendschau** [comment]
I think I fixed all issues with the previous/next-paging now. Not super sure because there are many ways to structure your pages with all kind of hierarchies, empty folders, hiden content, and more. But all my tests worked successfully now. It is not an issue of the theme, but an error in typemill core that produces the same issue in all themes.

If you want to download the fix and test it with your content, then please go to develop-branch of typemill: https://github.com/typemill/typemill/tree/develop

Simply update the system-folder and don't forget to do a composer update because the vendor folder of the github version is empty. 

Thank you!
Sebastian

**Comment by adioni** [comment]
I'm getting a "Slim Application Error - A website error has occurred. Sorry for the temporary inconvenience." message when I try and view the site.

Here's what's in the apache logs ( I have PHP version 8.0.7 installed on the system):

[Mon Jun 21 10:46:00.339854 2021] [php:warn] [pid 6095] [client 192.168.1.25.13:1034] PHP Warning:  Undefined array key "displayErrorDetails" in /var/www/typemill-dev/system/system.php on line 33, referer: http://webtest3.local/setup/welcome
[Mon Jun 21 10:46:06.145858 2021] [php:warn] [pid 3402] [client 192.168.1.25.13:1033] PHP Warning:  Undefined array key "displayErrorDetails" in /var/www/typemill-dev/system/system.php on line 33, referer: http://webtest3.local/tm/settings
[Mon Jun 21 10:46:08.954866 2021] [php:warn] [pid 3403] [client 192.168.1.25.13:1034] PHP Warning:  Undefined variable $structure in /var/www/typemill-dev/system/Controllers/PageController.php on line 385, referer: http://webtest3.local/tm/settings
[Mon Jun 21 10:46:08.954886 2021] [php:warn] [pid 3403] [client 192.168.1.25.13:1034] PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/typemill-dev/system/Controllers/PageController.php on line 433, referer: http://webtest3.local/tm/settings
[Mon Jun 21 10:46:08.957273 2021] [php:notice] [pid 3403] [client 192.168.1.25.13:1034] Slim Application Error:
Type: TypeError
Message: count(): Argument #1 ($value) must be of type Countable|array, bool given
File: /var/www/typemill-dev/system/Models/Folder.php
Line: 340
Trace: #0 /var/www/typemill-dev/system/Models/Folder.php(340): count()
#1 /var/www/typemill-dev/system/Controllers/PageController.php(212): Typemill\\Models\\Folder::getPagingForItem()
#2 [internal function]: Typemill\\Controllers\\PageController->index()
#3 /var/www/typemill-dev/system/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()
#4 /var/www/typemill-dev/system/vendor/slim/slim/Slim/Route.php(281): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()
#5 /var/www/typemill-dev/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\Route->__invoke()
#6 /var/www/typemill-dev/system/vendor/slim/slim/Slim/Route.php(268): Slim\\Route->callMiddlewareStack()
#7 /var/www/typemill-dev/system/vendor/slim/slim/Slim/App.php(503): Slim\\Route->run()
#8 /var/www/typemill-dev/system/Middleware/assetMiddleware.php(36): Slim\\App->__invoke()
#9 [internal function]: Typemill\\Middleware\\assetMiddleware->__invoke()
#10 /var/www/typemill-dev/system/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#11 [internal function]: Slim\\DeferredCallable->__invoke()
#12 /var/www/typemill-dev/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#13 /var/www/typemill-dev/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\App->Slim\\{closure}()
#14 /var/www/typemill-dev/system/vendor/slim/slim/Slim/App.php(392): Slim\\App->callMiddlewareStack()
#15 /var/www/typemill-dev/system/vendor/slim/slim/Slim/App.php(297): Slim\\App->process()
#16 /var/www/typemill-dev/index.php(7): Slim\\App->run()
#17 {main}
View in rendered output by enabling the "displayErrorDetails" setting.
, referer: http://webtest3.local/tm/settings

**Comment by trendschau** [comment]
Thank you for the detailed report and sorry for that, my mistake. I fixed the error and also the warnings and pushed to develop branch again. I will do some more tests in the next two days, but if you find the time to check it quickly, then it would be helpful. I do not use that scenario myself (I do not use the delete cache button at all), so this is a good opportunity to improve and cleanup the related code.

The homepage won't have a previous/next-pagination now, because its object is pretty different from all other page-objects and I want to avoid another complex check here. Not super sure if it is fine from a visitor's perspective...

**Comment by adioni** [comment]
I tried out the develop branch again. No more "Slim Application Error" and no errors. 

The previous/next-pagination now remains after I hide a page (and clear the cache); it's working great now; thanks!

Regarding _not_ clearing the clearing cache at all as part of my workflow: how long after adding a page/section in the admin screen and publishing that change should I be seeing that reflected on the frontend? You said ten minutes?

I've tried using the 'reload current page' button (and Ctrl+F5 for a hard refresh) in my web browser to shorten that time, but the new page is still not reflected right away. Now editing content on a pre-existing page seems shows up right away, but adding a new file / folder takes at least a few minutes. That's why I've been resorting sometimes to the 'delete the cache' button.

**Comment by trendschau** [comment]
I am glad to hear that it works now! 

Since the delete-cache-button is working correctly now, it is no problem to use it. Anyway, a hard page refresh is probably easier to use and it does not force Typemill to recreate all cache files, but only the cache for the navigation. The cache for the navigation is rebuild every 10 minutes. I just had a look into the code and noticed that I forgot to check the cache-control-header no-cache. I will fix that and then it should work more reliable, I hope.

**Comment by adioni** [comment]
Great, thanks again for all the help with this (though may be opening some completely unrelated issues, hope that's okay).
